// Run with Playwright MCP browser_run_code_unsafe(filename=absolute path).
async (page) => {
  await page.setViewportSize({ width: 1100, height: 800 });
  await page.goto("http://127.0.0.1:8765/tests/preview.html");
  const button = (name) => page.getByRole("button", { name, exact: true });
  const assert = (condition, message) => { if (!condition) throw Error(message); };
  const results = [];
  await button("会话统计").hover();
  if (await page.locator(".ztps-popup").count()) throw Error("hover must not open");
  await button("会话统计").focus();
  if (await page.locator(".ztps-popup").count()) throw Error("focus must not open");
  await button("会话统计").click();
  await button("会话统计").click();
  if (await page.locator(".ztps-popup").count()) throw Error("second click must close");
  await button("会话统计").click();
  const stats = await page.getByRole("region", { name: "会话统计详情" }).innerText();
  assert(stats.includes("5分51秒") && stats.includes("3分19秒") && stats.includes("1.2秒") && stats.includes("240 tok/s"), "statistics values");
  await button("Token 用量").click();
  if (!stats.includes("平均首 token 延迟（TTFT）") || !stats.includes("平均输出速度（TPS）")) throw Error("average labels");
  await page.mouse.move(10, 200);
  if (!(await page.locator(".ztps-popup").count())) throw Error("mouse leave must not close");
  assert(!stats.includes("有效调用") && !stats.includes("当前会话 · 本地近 30 天保留记录"), "no footer note");
  const usage = await page.getByRole("region", { name: "Token 用量详情" }).innerText();
  for (const value of ["5,807,056", "113,353", "5,625,984", "67,719", "98%"]) assert(usage.includes(value), `missing ${value}`);
  await page.screenshot({ path: "E:/Tools/zcode-patcher/tests/preview-usage.png" });
  results.push("screenshot metrics and click cards");
  await button("会话 B").click();
  await button("会话统计").filter({ hasText: "1 轮 · 2 次请求" }).waitFor();
  await button("延迟响应").click();
  await button("会话 B").click();
  await page.waitForTimeout(2800);
  assert((await button("会话统计").innerText()).includes("1 轮 · 2 次请求"), "stale response crossed sessions");
  results.push("session switching and stale-response isolation");
  await button("空会话").click();
  await button("Token 用量").waitFor({ state: "hidden" });
  await button("开始实时输出").click();
  await page.waitForTimeout(1500);
  assert(!(await button("会话统计").isVisible()), "live TPS must remain hidden before first model record");
  await button("结束输出").click();
  await button("首条模型记录落库").click();
  await button("会话统计").filter({ hasText: "0 轮 · 1 次请求" }).waitFor();
  await button("当前查询失败").click();
  await button("Token 用量").filter({ hasText: "统计不可用" }).waitFor();
  await button("当前查询失败").click();
  await button("查询失败").click();
  await button("Token 用量").waitFor({ state: "hidden" });
  results.push("hide before first model record, reveal after persistence, retain on transient failure");
  await button("会话 A").click(); await button("更新统计").click();
  await button("会话统计").filter({ hasText: "56 次请求" }).waitFor();
  await page.waitForTimeout(2200);
  assert((await button("会话统计").innerText()).includes("56 次请求"), "duplicate snapshot accumulation");
  results.push("refresh without duplicate accumulation");
  await button("Token 用量").focus();
  if (await page.locator(".ztps-popup").count()) throw Error("focus must not open");
  await page.keyboard.press("Enter");
  await page.getByRole("region", { name: "Token 用量详情" }).waitFor();
  await page.keyboard.press("Escape");
  await page.getByRole("region", { name: "Token 用量详情" }).waitFor({ state: "hidden" });
  results.push("keyboard focus and dismissal");
  await page.setViewportSize({ width: 320, height: 740 });
  await button("Token 用量").click();
  await page.screenshot({ path: "E:/Tools/zcode-patcher/tests/preview-narrow.png" });
  await button("切换主题").click(); await button("会话统计").click();
  await page.screenshot({ path: "E:/Tools/zcode-patcher/tests/preview-dark.png" });
  results.push("320px layout and dark theme screenshots");
  return results;
}
